
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.


title: Karishma Srikanth
email: karishma.r.srikanth@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website
github_username: karishmas26
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - assets/css/main.css


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - _posts
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Karishma Srikanth"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Data Scientist <br>
            USAID Office of HIV/AIDS"
  email  : "karishma.r.srikanth@gmail.com"
  github : "karishmas26"
  linkedin: "karishma-srikanth"
  speakerdeck: "karishmas26"

footer:
   links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/karishmas26"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/karishma-srikanth/"
    - label: "Speaker Deck"
      icon: "fab fa-fw fa-speaker-deck"
      url: "https://speakerdeck.com/karishmas26"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true
      breadcrumbs: true

custom_css:
  - /assets/css/main.css
     
      
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  work:
    output: true
    permalink: /work/:title/

# Analytics
analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : "G-NCWH48FZN7" # Replace with your Google Analytics tracking ID
    domain               : "karishma.github.io" # Replace with your domain  
